/**
 * We define our unit test code coverage thresholds here instead of directly in the jest configuration.
 * This is because we run the unit test in shards in the ado pipeline. In each shard, we run subset of the tests
 * but jest will still calculate the coverage for the entire project and set the coverage to 0 for the source files that were not tested in that shard.
 * This will cause the coverage threshold check to fail in the shard. So we dynamically remove the coverage threshold
 * from jest configuration when we run the tests in shards using environment variable DISABLE_COVERAGE_THRESHOLD.
 *
 * Instead, we collect the coverage file generated by jest in each shard and merge them using nyc package.
 * We also use nyc to check the coverage threshold for the merged coverage file,
 * and therefore we define the coverage threshold numbers in this nyc configuration file.
 *
 * WARNING: Do not lower these threshold values under any circumstances, except in the case of a critical incident requiring immediate mitigation.
 */
module.exports = {
  statements: 0,
  branches: 0,
  functions: 0,
  lines: 0,
};
