name: Checkout with Submodules
description: Checkout a repository with submodules

inputs:
  submodule-ssh-private-key:
    description: 'SSH private key for accessing submodules'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up SSH for submodules
      uses: webfactory/ssh-agent@v1
      with:
        ssh-private-key: ${{ inputs.submodule-ssh-private-key }}

    - name: Initialize submodules
      shell: bash
      run: git submodule update --init --recursive
