# We have a special case in this repo where this repo
# depends on submodules, which depend on itself for its
# yarn workspace packages - added using git ssh URIs.
# To work witht that we need to initialize ssh keys
# for the submodules and the main repository. This
# reusable workflow action sets all that up.

name: Submodule Initialization
description: Initializes Git submodules with SSH access.

inputs:
  submodule-ssh-private-key:
    description: 'SSH private key for accessing submodules'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up SSH for submodules
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: |
          ${{ inputs.submodule-ssh-private-key }}
          ${{ inputs.self-ssh-private-key }}

    - name: configure git to use SSH always
      shell: bash
      run: git config --global url."git@github.com:".insteadOf "https://github.com/"

    - name: Initialize submodules
      shell: bash
      run: git submodule update --init --recursive
