name: Checkout with Submodules
description: Checkout a repository with submodules

inputs:
  submodule-ssh-private-key:
    description: 'SSH private key for accessing submodules'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up SSH for submodules
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ inputs.submodule-ssh-private-key }}

    - name: Configure Git for private dependencies
      run: git config --global url."https://x-access-token:${{ secrets.GH_PAT_FOR_DEPS }}@github.com/".insteadOf "https://github.com/"

    - name: Initialize submodules
      shell: bash
      run: git submodule update --init --recursive
