name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving 1fe! Please describe your feature request as clearly as possible.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please check that you've completed the following
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: I have read the documentation
          required: true
        - label: This feature doesn't exist in the latest version
          required: true

  - type: input
    id: package
    attributes:
      label: Package
      description: Which 1fe package would this feature affect?
      placeholder: "@1fe/server, @1fe/shell, @1fe/cli, @1fe/create-1fe-app, or new package"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen
      placeholder: "I would like..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How would this feature benefit 1fe users?
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (simple configuration or UI change)
        - Medium (new component or moderate logic)
        - High (architectural changes or new packages)
        - Unknown

  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes?
      options:
        - label: This feature would require breaking changes
        - label: This feature is backward compatible

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: If applicable, provide code examples of how this feature would be used
      render: typescript

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here