name: Setup Submodules
description: Set up Git submodules for the project

inputs:
  submodule-ssh-private-key:
    description: SSH private key for accessing submodules
    required: true
  self-ssh-private-key:
    description: SSH private key for accessing the repository itself
    required: true

runs:
  using: 'composite'
  steps:
    - name: Mark workspace as safe
      shell: bash
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    # TODO #61 - this action goes away when our repos become public.
    - name: Set up SSH for submodules and yarn
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: |
          ${{ inputs.submodule-ssh-private-key }}
          ${{ inputs.self-ssh-private-key }}

    - name: Force HTTPS for submodules (GitHub)
      shell: bash
      if: steps.checkout.outputs.submodules != 'true' # Only run if checkout didn't handle submodules
      run: git config --global url."https://github.com/".insteadOf "git@github.com:"

    - name: Initialize submodules
      shell: bash
      run: git submodule update --init --recursive --remote

    # TODO #61 - this action goes away when our repos become public.
    - name: configure git to use SSH always
      shell: bash
      run: git config --global url."git@github.com:".insteadOf "https://github.com/" # Force SSH for all GitHub URLs after submodule init

    - name: Install submodule dependencies
      shell: bash
      run: |
        # All submodules are using Yarn workspaces, so we can install all dependencies at once.
        yarn workspaces foreach --all install --no-immutable
