name: Checkout with Submodules

on:
  workflow_call:
    inputs:
      submodules:
        description: 'Whether to checkout submodules recursively'
        required: true
        type: boolean
        default: false
      checkout-options:
        description: 'Additional options to pass to the checkout action'
        required: false
        type: object
        default: {}

steps:
  - name: Checkout with submodules
    if: ${{ inputs.submodules }}
    uses: actions/checkout@v4
    with:
      submodules: recursive
      ${{ inputs.checkout-options }}

  - name: Set up SSH for submodules
    if: ${{ inputs.submodules }}
    uses: webfactory/ssh-agent@v1
    with:
      ssh-private-key: ${{ secrets.SUBMODULE_SSH_PRIVATE_KEY }}

  - name: Initialize submodules
    if: ${{ inputs.submodules }}
    run: git submodule update --init --recursive

  - name: Checkout without submodules
    if: ${{ !inputs.submodules }}
    uses: actions/checkout@v4
    with:
      ${{ inputs.checkout-options }}
