name: Setup Node
description: Set up Node.js environment for the project

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: https://registry.npmjs.org/
        cache: 'yarn'

    - name: Cache for Turbo
      uses: rharkor/caching-for-turbo@v1.8

    - name: Install dependencies
      shell: bash
      run: yarn install --no-immutable # not using --immutable because some submodule lockfiles may change and its ok
